#!/bin/sh

# chmod 755 publish
# ./publish

# run only on developer branch

# tutorial: https://jaspervdj.be/hakyll/tutorials/github-pages-tutorial.html

CYAN='\033[1;36m'
NC='\033[0m'      # No Color

echo "🌚🌚🌚"
# Temporarily store uncommited changes
git stash

# Verify correct branch
git checkout develop

echo "${CYAN}Type anything to continue or control+c to abort: ${NC}"
read input_variable
echo "${CYAN}Nice choice, $input_variable!${NC}"

# Build new files
cd blog
stack build
stack exec blog build

# Get previous files
git fetch --all
# git branch -D master
git checkout -b master --track origin/master

# Overwrite existing files with new files
cd ..
cp -a blog/_site/. .

# Commit
git add -A
git status
echo "${CYAN}Type anything to continue or control+c to abort: ${NC}"
read input_variable
echo "${CYAN}Here we go${NC}"
git commit -m "Publish changes 👏"

# Push
git push origin master:master

# Restoration
git checkout develop
git branch -D master
git stash pop
