#!/bin/sh

# chmod 755 setup
# ./publish

echo "🌚🌚🌚"
# Temporarily store uncommited changes
git stash

# Verify correct branch
git checkout develop

# Build new files
cd blog
stack build
stack exec blog build

# Get previous files
git fetch --all
git checkout -b master --track origin/master

# Overwrite existing files with new files
cd ..
cp -a blog/_site/. .

# Commit
git add -A
git commit -m "Publish changes 👏"

# Push
git push origin master:master

# Restoration
git checkout develop
git branch -D master
git stash pop
